### ISSUE TITLE
Node Version Test fails.

### ISSUE THREAD

**Issue by GodTanu** [nemgrouplimited/symbol-node-monitoring-agent#3]
Sometimes the node version is 0.0.0.0 and fails.

![image](https://user-images.githubusercontent.com/20492223/109614620-3629d280-7b76-11eb-9932-990fc68b3a1d.png)

![image](https://user-images.githubusercontent.com/20492223/109614674-48a40c00-7b76-11eb-806a-8d91e1e1316f.png)

It is unlikely to be a problem on the node side.

**Comment by AnthonyLaw** [comment]
Hi there, I was doing some log on round #129
the message was 

```
problems accessing node http://x.x.x.x:3000: {"statusCode":503,"statusMessage":"Service Unavailable","body":"{\"code\":\"ServiceUnavailable\",\"message\":\"connection failed\"}"}
```

We are still looking for more detail.

**Comment by AnthonyLaw** [comment]
Hi there, after some investigation.
It not related to the Agent node itself.
We didn't see this problem in NGL SuperNode.

It should cause on the SuperNode's REST Endpoint.
as the error message showing that when accessing the REST API.

`{"statusCode":503,"statusMessage":"Service Unavailable","body":"{\"code\":\"ServiceUnavailable\",\"message\":\"connection failed\"}"}`

I will close this for now.
if you have any related log from REST let me know.
we can re-open this issue for further investigation.

**Comment by GodTanu** [comment]
I am using two different VPS's and the problem is recurring.
Please let me know how I can investigate.
It is only the **node version** that cannot be passed.

Both v0.10.0.8 

VPS.1
![image](https://user-images.githubusercontent.com/20492223/110398998-5a2a6e00-80b8-11eb-9cbf-38cf42a2e03f.png)
![image](https://user-images.githubusercontent.com/20492223/110399350-0ec48f80-80b9-11eb-92b1-d76f9423d265.png)
![image](https://user-images.githubusercontent.com/20492223/110399110-9231b100-80b8-11eb-998e-3a6498673309.png)
![image](https://user-images.githubusercontent.com/20492223/110399135-a1186380-80b8-11eb-9c3e-83cb277abda1.png)
![image](https://user-images.githubusercontent.com/20492223/110399154-ac6b8f00-80b8-11eb-89d0-e88965cd8c0c.png)

VPS.2
![image](https://user-images.githubusercontent.com/20492223/110399202-c0af8c00-80b8-11eb-9233-39b67362606d.png)
![image](https://user-images.githubusercontent.com/20492223/110399238-d6bd4c80-80b8-11eb-9d11-f8a4e4f3fc6d.png)
![image](https://user-images.githubusercontent.com/20492223/110399295-f3f21b00-80b8-11eb-8787-9d2932293bc5.png)
![image](https://user-images.githubusercontent.com/20492223/110399326-010f0a00-80b9-11eb-8755-7cf24178f6ee.png)
![image](https://user-images.githubusercontent.com/20492223/110399378-1be17e80-80b9-11eb-9573-21a03a8487aa.png)

**Comment by GodTanu** [comment]
Now,Version information 0.0.0.0 has recurred.
Is this log the problem?

target/gateways/rest-gateway/logs/catapult-rest.log

`{
  jse_shortmsg: 'connection failed',
  jse_info: {},
  message: 'caught error 503 connection failed',
  body: { code: 'ServiceUnavailable', message: 'connection failed' },
  level: 'error',
  stack: 'ServiceUnavailableError: connection failed\n' +
    '    at Object.createServiceUnavailableError (/app/catapult-rest/rest/_build/server/errors.js:56:44)\n' +
    '    at TLSSocket.<anonymous> (/app/catapult-rest/rest/_build/connection/catapultConnection.js:27:53)\n' +
    '    at Object.onceWrapper (events.js:422:26)\n' +
    '    at TLSSocket.emit (events.js:327:22)\n' +
    '    at net.js:674:12\n' +
    '    at TCP.done (_tls_wrap.js:567:7)',
  timestamp: '2021-03-09T00:01:50.152Z'
}
{
  jse_shortmsg: 'connection failed',
  jse_info: {},
  message: 'caught error 503 connection failed',
  body: { code: 'ServiceUnavailable', message: 'connection failed' },
  level: 'error',
  stack: 'ServiceUnavailableError: connection failed\n' +
    '    at Object.createServiceUnavailableError (/app/catapult-rest/rest/_build/server/errors.js:56:44)\n' +
    '    at TLSSocket.<anonymous> (/app/catapult-rest/rest/_build/connection/catapultConnection.js:27:53)\n' +
    '    at Object.onceWrapper (events.js:422:26)\n' +
    '    at TLSSocket.emit (events.js:327:22)\n' +
    '    at net.js:674:12\n' +
    '    at TCP.done (_tls_wrap.js:567:7)',
  timestamp: '2021-03-09T00:01:50.155Z'
}
{
  jse_shortmsg: 'connection failed',
  jse_info: {},
  message: 'caught error 503 connection failed',
  body: { code: 'ServiceUnavailable', message: 'connection failed' },
  level: 'error',
  stack: 'ServiceUnavailableError: connection failed\n' +
    '    at Object.createServiceUnavailableError (/app/catapult-rest/rest/_build/server/errors.js:56:44)\n' +
    '    at TLSSocket.<anonymous> (/app/catapult-rest/rest/_build/connection/catapultConnection.js:27:53)\n' +
    '    at Object.onceWrapper (events.js:422:26)\n' +
    '    at TLSSocket.emit (events.js:327:22)\n' +
    '    at net.js:674:12\n' +
    '    at TCP.done (_tls_wrap.js:567:7)',
  timestamp: '2021-03-09T00:01:50.158Z'
}
{
  jse_shortmsg: 'connection failed',
  jse_info: {},
  message: 'caught error 503 connection failed',
  body: { code: 'ServiceUnavailable', message: 'connection failed' },
  level: 'error',
  stack: 'ServiceUnavailableError: connection failed\n' +
    '    at Object.createServiceUnavailableError (/app/catapult-rest/rest/_build/server/errors.js:56:44)\n' +
    '    at TLSSocket.<anonymous> (/app/catapult-rest/rest/_build/connection/catapultConnection.js:27:53)\n' +
    '    at Object.onceWrapper (events.js:422:26)\n' +
    '    at TLSSocket.emit (events.js:327:22)\n' +
    '    at net.js:674:12\n' +
    '    at TCP.done (_tls_wrap.js:567:7)',
  timestamp: '2021-03-09T00:01:50.159Z'
}
{
  jse_shortmsg: 'connection failed',
  jse_info: {},
  message: 'caught error 503 connection failed',
  body: { code: 'ServiceUnavailable', message: 'connection failed' },
  level: 'error',
  stack: 'ServiceUnavailableError: connection failed\n' +
    '    at Object.createServiceUnavailableError (/app/catapult-rest/rest/_build/server/errors.js:56:44)\n' +
    '    at TLSSocket.<anonymous> (/app/catapult-rest/rest/_build/connection/catapultConnection.js:27:53)\n' +
    '    at Object.onceWrapper (events.js:422:26)\n' +
    '    at TLSSocket.emit (events.js:327:22)\n' +
    '    at net.js:674:12\n' +
    '    at TCP.done (_tls_wrap.js:567:7)',
  timestamp: '2021-03-09T00:01:50.161Z'
}
{
  jse_shortmsg: 'connection failed',
  jse_info: {},
  message: 'caught error 503 connection failed',
  body: { code: 'ServiceUnavailable', message: 'connection failed' },
  level: 'error',
  stack: 'ServiceUnavailableError: connection failed\n' +
    '    at Object.createServiceUnavailableError (/app/catapult-rest/rest/_build/server/errors.js:56:44)\n' +
    '    at TLSSocket.<anonymous> (/app/catapult-rest/rest/_build/connection/catapultConnection.js:27:53)\n' +
    '    at Object.onceWrapper (events.js:422:26)\n' +
    '    at TLSSocket.emit (events.js:327:22)\n' +
    '    at net.js:674:12\n' +
    '    at TCP.done (_tls_wrap.js:567:7)',
  timestamp: '2021-03-09T00:01:50.163Z'
}`

**Comment by GodTanu** [comment]
Is it relevant to this issue?

https://github.com/nemtech/catapult-rest/issues/562
https://github.com/nemtech/catapult-rest/issues/563

**Comment by AnthonyLaw** [comment]
Thanks 
it forwards to the REST team to investigate it.

**Comment by rg911** [comment]
Does a restart of the rest gateway solve this? the rest error means the tls handshake failed, the most common cause is the certificates used by rest (same as the API node) were wrong.

**Comment by GodTanu** [comment]
How do I restart the rest gateway?
Not by restarting the node?

**Comment by GodTanu** [comment]
@rg911 @AnthonyLaw 
I have performed a reboot of the node (bootstrap stop/run) but the situation has not improved.


> {
  message: 'connecting to api-node:7900',
  level: 'verbose',
  timestamp: '2021-03-10T00:10:11.249Z'
}
{
  jse_shortmsg: 'connection failed',
  jse_info: {},
  message: 'caught error 503 connection failed',
  body: { code: 'ServiceUnavailable', message: 'connection failed' },
  level: 'error',
  stack: 'ServiceUnavailableError: connection failed\n' +
    '    at Object.createServiceUnavailableError (/app/catapult-rest/rest/_build/server/errors.js:56:44)\n' +
    '    at TLSSocket.<anonymous> (/app/catapult-rest/rest/_build/connection/catapultConnection.js:27:53)\n' +
    '    at Object.onceWrapper (events.js:422:26)\n' +
    '    at TLSSocket.emit (events.js:327:22)\n' +
    '    at net.js:674:12\n' +
    '    at TCP.done (_tls_wrap.js:567:7)',
  timestamp: '2021-03-10T00:10:11.318Z'
}
{
  jse_shortmsg: 'connection failed',
  jse_info: {},
  message: 'caught error 503 connection failed',
  body: { code: 'ServiceUnavailable', message: 'connection failed' },
  level: 'error',
  stack: 'ServiceUnavailableError: connection failed\n' +
    '    at Object.createServiceUnavailableError (/app/catapult-rest/rest/_build/server/errors.js:56:44)\n' +
    '    at TLSSocket.<anonymous> (/app/catapult-rest/rest/_build/connection/catapultConnection.js:27:53)\n' +
    '    at Object.onceWrapper (events.js:422:26)\n' +
    '    at TLSSocket.emit (events.js:327:22)\n' +
    '    at net.js:674:12\n' +
    '    at TCP.done (_tls_wrap.js:567:7)',
  timestamp: '2021-03-10T00:10:11.322Z'
}
{
  jse_shortmsg: 'connection failed',
  jse_info: {},
  message: 'caught error 503 connection failed',
  body: { code: 'ServiceUnavailable', message: 'connection failed' },
  level: 'error',
  stack: 'ServiceUnavailableError: connection failed\n' +
    '    at Object.createServiceUnavailableError (/app/catapult-rest/rest/_build/server/errors.js:56:44)\n' +
    '    at TLSSocket.<anonymous> (/app/catapult-rest/rest/_build/connection/catapultConnection.js:27:53)\n' +
    '    at Object.onceWrapper (events.js:422:26)\n' +
    '    at TLSSocket.emit (events.js:327:22)\n' +
    '    at net.js:674:12\n' +
    '    at TCP.done (_tls_wrap.js:567:7)',
  timestamp: '2021-03-10T00:10:11.332Z'
}
{
  jse_shortmsg: 'connection failed',
  jse_info: {},
  message: 'caught error 503 connection failed',
  body: { code: 'ServiceUnavailable', message: 'connection failed' },
  level: 'error',
  stack: 'ServiceUnavailableError: connection failed\n' +
    '    at Object.createServiceUnavailableError (/app/catapult-rest/rest/_build/server/errors.js:56:44)\n' +
    '    at TLSSocket.<anonymous> (/app/catapult-rest/rest/_build/connection/catapultConnection.js:27:53)\n' +
    '    at Object.onceWrapper (events.js:422:26)\n' +
    '    at TLSSocket.emit (events.js:327:22)\n' +
    '    at net.js:674:12\n' +
    '    at TCP.done (_tls_wrap.js:567:7)',
  timestamp: '2021-03-10T00:10:11.336Z'
}
{
  jse_shortmsg: 'connection failed',
  jse_info: {},
  message: 'caught error 503 connection failed',
  body: { code: 'ServiceUnavailable', message: 'connection failed' },
  level: 'error',
  stack: 'ServiceUnavailableError: connection failed\n' +
    '    at Object.createServiceUnavailableError (/app/catapult-rest/rest/_build/server/errors.js:56:44)\n' +
    '    at TLSSocket.<anonymous> (/app/catapult-rest/rest/_build/connection/catapultConnection.js:27:53)\n' +
    '    at Object.onceWrapper (events.js:422:26)\n' +
    '    at TLSSocket.emit (events.js:327:22)\n' +
    '    at net.js:674:12\n' +
    '    at TCP.done (_tls_wrap.js:567:7)',
  timestamp: '2021-03-10T00:10:11.346Z'
}
{
  message: 'connecting to api-node:7900',
  level: 'verbose',
  timestamp: '2021-03-10T00:10:13.901Z'
}

**Comment by AnthonyLaw** [comment]
Fixes the problem with sent few more request to get the node version,  if there is 503 happen.
